language: node_js
node_js:
  - "12"
  - "13"
  - "14"
  - "15"
cache:
  directories:
    - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=b3658fd0ee9f4a540c536bf6b43b81ac3794b85fbc991abca086a90296f7b381
    - MONGO_HOST="mongodb://localhost:27017/test"

before_install:
  - npm i -g npm@latest
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm install
  - npm install --no-save @rxstack/core@^0.7 @rxstack/exceptions@^0.6 @rxstack/platform@^0.7 @rxstack/query-filter@^0.6 @rxstack/security@^0.7 @rxstack/async-event-dispatcher@^0.6 @rxstack/service-registry@^0.6 winston@^3.3.3
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

services:
  - mongodb

